### ISSUE TITLE
Bro , Want to ask ,

### ISSUE THREAD

**Issue by kingsalman99** [shennguyenrs/study_projects#10]
How to use ,Iban Checker and Generator bro..? iam noob bro

**Comment by shennguyenrs** [comment]
Hi, I have updated it to a new repository and write a new readme for it. I actually a noob too, thank you for interested in my project.  If you have more ideas to improve it, please let me know. I still need to learn too.

**Comment by kingsalman99** [comment]
thank you  bro ,U are the best ,good job
